remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: [Enhancing Efficiency in Food Delivery]
description: [A portfolio site showcasing the integration of advanced data structures and algorithms in the online food delivery ecosystem.]
